name: comsw4733_hw4
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.9
  - numpy=1.22.2
  - pybullet=3.21
  - py-opencv=4.5.5
  - scipy=1.8.0
  - pandas=1.4.1
  - matplotlib=3.5.1
  - tqdm=4.63
  - scikit-image=0.19.2
  - imgaug=0.4.0
  - pytorch=1.11.0
  - torchvision=0.12.0
